### ISSUE TITLE
关于负载均衡库是否选择balancer

### ISSUE THREAD

**Issue by ghost** [panjf2000/goproxy#7]
你好同事~

这个是目前一直在维护的库，之后会增加更多的负载均衡算法，生态更加活跃稳定，想听听同事的意见
https://github.com/zehuamama/balancer

**Comment by panjf2000** [comment]
什么意思？让我用你的库替换现在内置的？

**Comment by ghost** [comment]
是这个意思~

**Comment by panjf2000** [comment]
你这个库不也有proxy功能吗，相当于是和goproxy一样的东西了，goproxy现在我也没什么时间去更新了，你要是有兴趣可以提个PR。
